import { StyleSheet } from "react-native";

export default StyleSheet.create({
     container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
  },
  header: {
    paddingVertical: 48,
    paddingHorizontal: 24,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 30,
    fontFamily: 'Outfit-Bold',
    color: '#fff',
  },
  headerSubtitle: {
    fontSize: 16,
    fontFamily: 'Outfit',
    color: '#fff',
    marginTop: 8,
  },
  listContainer: {
    padding: 20,
    paddingBottom: 20,
  },
  cartItemCard: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: 15,
    marginBottom: 15,
    elevation: 5,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    padding: 16,
    alignItems: 'center',
  },
  cartImage: {
    width: 80,
    height: 80,
    borderRadius: 10,
  },
  placeholderImage: {
    width: 80,
    height: 80,
    backgroundColor: '#f0f0f0',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  cartItemInfo: {
    flex: 1,
    marginLeft: 16,
  },
  cartItemName: {
    fontSize: 18,
    fontFamily: 'Outfit-SemiBold',
    color: '#333',
  },
  cartItemPrice: {
    fontSize: 14,
    fontFamily: 'Outfit',
    color: '#666',
    marginTop: 6,
  },
  quantityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    backgroundColor: '#f8f8f8',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  quantity: {
    fontSize: 16,
    fontFamily: 'Outfit',
    color: '#333',
    marginHorizontal: 16,
    minWidth: 24,
    textAlign: 'center',
  },
  cartItemTotal: {
    fontSize: 16,
    fontFamily: 'Outfit-SemiBold',
    color: '#eb7d34',
    marginTop: 8,
  },
  removeButton: {
    padding: 10,
  },
  disabledButton: {
    opacity: 0.5,
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
  },
  emptyText: {
    fontSize: 18,
    fontFamily: 'Outfit',
    color: '#333',
    marginTop: 12,
    textAlign: 'center',
  },
  menuButton: {
    backgroundColor: '#eb7d34',
    paddingHorizontal: 28,
    paddingVertical: 14,
    borderRadius: 12,
    marginTop: 20,
  },
  menuButtonText: {
    fontSize: 16,
    fontFamily: 'Outfit',
    color: '#fff',
  },
  checkoutContainer: {
    backgroundColor: '#fff',
    padding: 24,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    elevation: 5,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: -4 },
  },
  totalContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  totalLabel: {
    fontSize: 18,
    fontFamily: 'Outfit',
    color: '#333',
  },
  totalAmount: {
    fontSize: 20,
    fontFamily: 'Outfit-Bold',
    color: '#eb7d34',
  },
  paymentContainer: {
    marginBottom: 24,
  },
  paymentLabel: {
    fontSize: 16,
    fontFamily: 'Outfit',
    color: '#333',
    marginBottom: 12,
  },
  paymentOptions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  paymentOption: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ddd',
    marginHorizontal: 4,
    alignItems: 'center',
  },
  selectedPaymentOption: {
    backgroundColor: '#eb7d34',
    borderColor: '#eb7d34',
  },
  paymentOptionText: {
    fontSize: 14,
    fontFamily: 'Outfit',
    color: '#666',
  },
  selectedPaymentOptionText: {
    color: '#fff',
  },
  checkoutButton: {
    backgroundColor: '#eb7d34',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  checkoutButtonText: {
    fontSize: 18,
    fontFamily: 'Outfit-Bold',
    color: '#fff',
  },
  loadingText: {
    fontSize: 16,
    fontFamily: 'Outfit',
    color: '#333',
    marginTop: 12,
  },
  errorText: {
    fontSize: 16,
    fontFamily: 'Outfit',
    color: '#333',
    marginTop: 12,
    textAlign: 'center',
    paddingHorizontal: 20,
  },
})