import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f5f5f5',
    },
    center: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#f5f5f5',
    },
    header: {
        paddingVertical: 40,
        paddingHorizontal: 20,
        borderBottomLeftRadius: 20,
        borderBottomRightRadius: 20,
    },
    headerContent: {
        marginTop: 20,
    },
    greeting: {
        fontSize: 28,
        fontFamily: 'Outfit-Bold',
        color: '#fff',
    },
    name: {
        fontFamily: 'Outfit-Bold',
        color: '#FFFFFF',
    },
    subGreeting: {
        fontSize: 16,
        fontFamily: 'Outfit',
        color: '#fff',
        marginTop: 8,
    },
    sectionContainer: {
        marginTop: 20,
    },
    sectionTitle: {
        fontSize: 20,
        fontFamily: 'Outfit-SemiBold',
        marginLeft: 20,
        marginBottom: 15,
        color: '#333',
    },
    promoContainer: {
        marginTop: 20,
    },
    promoCard: {
        marginRight: 15,
        borderRadius: 15,
        overflow: 'hidden',
        elevation: 5,
        shadowColor: '#000',
        shadowOpacity: 0.2,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 4 },
    },
    promoImage: {
        width: 300,
        height: 160,
        borderRadius: 15,
    },
    promoGradient: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        height: 60,
        justifyContent: 'center',
        paddingHorizontal: 15,
    },
    promoTitle: {
        fontSize: 16,
        fontFamily: 'Outfit-SemiBold',
        color: '#fff',
    },
    categoryCard: {
        alignItems: 'center',
        marginRight: 15,
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 12,
        elevation: 3,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 5,
    },
    categoryIcon: {
        width: 60,
        height: 60,
        borderRadius: 30,
        marginBottom: 8,
    },
    categoryText: {
        fontFamily: 'Outfit',
        fontSize: 14,
        color: '#333',
    },
    dishCard: {
        marginRight: 15,
        width: 160,
        borderRadius: 15,
        backgroundColor: '#fff',
        elevation: 5,
        shadowColor: '#000',
        shadowOpacity: 0.2,
        shadowRadius: 8,
        overflow: 'hidden',
    },
    dishImage: {
        width: '100%',
        height: 110,
        borderTopLeftRadius: 15,
        borderTopRightRadius: 15,
    },
    dishInfo: {
        padding: 10,
    },
    dishName: {
        fontFamily: 'Outfit',
        fontSize: 15,
        color: '#333',
    },
    ratingContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 4,
    },
    dishRating: {
        fontFamily: 'Outfit',
        fontSize: 13,
        color: '#555',
        marginLeft: 4,
    },
    dishPrice: {
        fontFamily: 'Outfit-SemiBold',
        fontSize: 15,
        color: '#eb7d34',
        marginTop: 6,
    },
    ctaContainer: {
        marginVertical: 30,
        paddingHorizontal: 20,
    },
    ctaGradient: {
        borderRadius: 15,
        padding: 20,
        alignItems: 'center',
    },
    ctaTitle: {
        fontSize: 22,
        fontFamily: 'Outfit-Bold',
        color: '#fff',
        marginBottom: 10,
    },
    ctaSubtitle: {
        fontSize: 16,
        fontFamily: 'Outfit',
        color: '#fff',
        marginBottom: 20,
        textAlign: 'center',
    },
    ctaButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff',
        borderRadius: 25,
        paddingVertical: 12,
        paddingHorizontal: 20,
        elevation: 3,
    },
    ctaButtonText: {
        fontSize: 16,
        fontFamily: 'Outfit-SemiBold',
        color: '#eb7d34',
        marginRight: 10,
    },
    ctaButtonIcon: {
        marginLeft: 5,
    },
})