import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f5f5' },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#f5f5f5' },
  header: { paddingVertical: 40, paddingHorizontal: 20, borderBottomLeftRadius: 20, borderBottomRightRadius: 20, alignItems: 'center' },
  headerTitle: { fontSize: 28, fontFamily: 'Outfit-Bold', color: '#fff' },
  headerSubtitle: { fontSize: 16, fontFamily: 'Outfit-Regular', color: '#fff', marginTop: 8 },
  filterContainer: { paddingHorizontal: 20, paddingTop: 10 },
  categoryButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#eb7d34', paddingVertical: 8, paddingHorizontal: 12, borderRadius: 8, marginBottom: 10 },
  categoryButtonText: { fontSize: 14, fontFamily: 'Outfit-Medium', color: '#fff', marginRight: 8 },
  dietaryToggleContainer: { flexDirection: 'row', justifyContent: 'space-between', gap: 8 },
  dietaryButton: { flex: 1, paddingVertical: 8, borderRadius: 8, borderWidth: 1, borderColor: '#eb7d34', alignItems: 'center', backgroundColor: '#fff' },
  dietaryButtonActive: { backgroundColor: '#eb7d34' },
  dietaryButtonText: { fontSize: 12, fontFamily: 'Outfit-Medium', color: '#333' },
  modalContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.5)' },
  modalContent: { backgroundColor: '#fff', borderRadius: 12, padding: 15, width: '80%', maxHeight: '40%' },
  modalTitle: { fontSize: 18, fontFamily: 'Outfit-Bold', color: '#333', textAlign: 'center', marginBottom: 15 },
  modalItem: { paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#f0f0f0', alignItems: 'center' },
  modalItemText: { fontSize: 14, fontFamily: 'Outfit-Medium', color: '#333' },
  modalCloseButton: { marginTop: 15, backgroundColor: '#eb7d34', paddingVertical: 8, borderRadius: 8, alignItems: 'center' },
  modalCloseButtonText: { fontSize: 14, fontFamily: 'Outfit-Medium', color: '#fff' },
  listContainer: { padding: 20, paddingBottom: 100 },
  dishCard: { flexDirection: 'row', backgroundColor: '#fff', borderRadius: 12, marginBottom: 12, elevation: 4, shadowColor: '#000', shadowOpacity: 0.2, shadowRadius: 6, shadowOffset: { width: 0, height: 3 }, overflow: 'hidden' },
  dishImage: { width: 80, height: 80, borderTopLeftRadius: 12, borderBottomLeftRadius: 12 },
  placeholderImage: { width: 80, height: 80, backgroundColor: '#f0f0f0', justifyContent: 'center', alignItems: 'center', borderTopLeftRadius: 12, borderBottomLeftRadius: 12 },
  dishInfo: { flex: 1, padding: 12 },
  dishName: { fontSize: 16, fontFamily: 'Outfit-SemiBold', color: '#333' },
  dishDescription: { fontSize: 12, fontFamily: 'Outfit-Regular', color: '#666', marginTop: 4 },
  dishDetails: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 6 },
  dishCategory: { fontSize: 12, fontFamily: 'Outfit-Medium', color: '#eb7d34' },
  dishDietory: { fontSize: 12, fontFamily: 'Outfit-Medium', color: '#555' },
  dishFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 8 },
  dishPrice: { fontSize: 14, fontFamily: 'Outfit-SemiBold', color: '#eb7d34' },
  dishPortion: { fontSize: 12, fontFamily: 'Outfit-Regular', color: '#555', backgroundColor: '#f8f8f8', paddingHorizontal: 6, paddingVertical: 3, borderRadius: 8 },
  addButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#eb7d34', paddingHorizontal: 10, paddingVertical: 5, borderRadius: 6 },
  addedButton: { backgroundColor: '#28a745' },
  addButtonText: { fontSize: 12, fontFamily: 'Outfit-Medium', color: '#fff', marginLeft: 4 },
  menuButton: { backgroundColor: '#eb7d34', paddingHorizontal: 24, paddingVertical: 12, borderRadius: 10, marginTop: 15 },
  menuButtonText: { fontSize: 14, fontFamily: 'Outfit-Medium', color: '#fff' },
  loadingText: { fontSize: 14, fontFamily: 'Outfit-Regular', color: '#333', marginTop: 8 },
  errorText: { fontSize: 14, fontFamily: 'Outfit-Regular', color: '#333', marginTop: 8, textAlign: 'center' },
  emptyContainer: { alignItems: 'center', justifyContent: 'center', paddingVertical: 40 },
  emptyText: { fontSize: 14, fontFamily: 'Outfit-Regular', color: '#333', marginTop: 8, textAlign: 'center' },
  notificationContainer: { position: 'absolute', top: 30, left: 15, right: 15, padding: 12, borderRadius: 8, alignItems: 'center', elevation: 8, shadowColor: '#000', shadowOpacity: 0.2, shadowRadius: 4, shadowOffset: { width: 0, height: 2 } },
  notificationText: { fontSize: 14, fontFamily: 'Outfit-Medium', color: '#fff' },
});